# Capitulo 46: Rating Sports Teams

In [285]:
import pandas as pd
import numpy as np

In [286]:
df_scores = pd.read_csv('2010-2026_scores.csv')

df_scores.head()

,Season,Week,GameStatus,GameSlot,GameDate,AwayTeam,AwayScore,HomeTeam,HomeScore
0,2010,HALL OF FAME,FINAL,Sunday,August 8th,DAL,16.0,CIN,7.0
1,2010,PRESEASON WEEK 1,FINAL,Thursday,August 12th,CAR,12.0,BAL,17.0
2,2010,PRESEASON WEEK 1,FINAL,Thursday,August 12th,NO,24.0,NE,27.0
3,2010,PRESEASON WEEK 1,FINAL,Thursday,August 12th,OAK,17.0,DAL,9.0
4,2010,PRESEASON WEEK 1,FINAL,Friday,August 13th,BUF,17.0,WAS,42.0

In [287]:
df_2016 = df_scores[df_scores['Season'] == 2016]

# Quedarnos solo con la regular season
df_2016 = df_2016[df_2016.Week.str.startswith('WEEK')  ]

df_2016 = df_2016.dropna()

df_2016.head()

,Season,Week,GameStatus,GameSlot,GameDate,AwayTeam,AwayScore,HomeTeam,HomeScore
2278,2016,WEEK 1,FINAL,Thursday,September 8th,CAR,20.0,DEN,21.0
2279,2016,WEEK 1,FINAL,Sunday,September 11th,TB,31.0,ATL,24.0
2280,2016,WEEK 1,FINAL,Sunday,September 11th,BUF,7.0,BAL,13.0
2281,2016,WEEK 1,FINAL,Sunday,September 11th,CHI,14.0,HOU,23.0
2282,2016,WEEK 1,FINAL,Sunday,September 11th,GB,27.0,JAC,23.0

In [288]:
df_2016.describe()

       Season   AwayScore   HomeScore
count   256.0  256.000000  256.000000
mean   2016.0   21.492188   24.058594
std       0.0    9.337671    9.205736
min    2016.0    0.000000    0.000000
25%    2016.0   15.000000   17.000000
50%    2016.0   21.000000   24.000000
75%    2016.0   27.000000   30.000000
max    2016.0   48.000000   49.000000

In [289]:

df_scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6185 entries, 0 to 6184
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      6185 non-null   int64
 1   Week        6185 non-null   object
 2   GameStatus  6185 non-null   object
 3   GameSlot    5591 non-null   object
 4   GameDate    5591 non-null   object
 5   AwayTeam    6185 non-null   object
 6   AwayScore   5332 non-null   float64
 7   HomeTeam    5591 non-null   object
 8   HomeScore   5332 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 435.0+ KB

In [290]:
weeks = df_2016['Week'].unique()

print(weeks)

['WEEK 1' 'WEEK 2' 'WEEK 3' 'WEEK 4' 'WEEK 5' 'WEEK 6' 'WEEK 7' 'WEEK 8'
 'WEEK 9' 'WEEK 10' 'WEEK 11' 'WEEK 12' 'WEEK 13' 'WEEK 14' 'WEEK 15'
 'WEEK 16' 'WEEK 17']

In [291]:
cnt_weeks = df_2016.groupby('Week').size()

cnt_weeks

Week
WEEK 1     16
WEEK 10    14
WEEK 11    14
WEEK 12    16
WEEK 13    15
WEEK 14    16
WEEK 15    16
WEEK 16    16
WEEK 17    16
WEEK 2     16
WEEK 3     16
WEEK 4     15
WEEK 5     14
WEEK 6     15
WEEK 7     15
WEEK 8     13
WEEK 9     13
dtype: int64

In [292]:
df_2016[df_2016['Week'] == 'WEEK 10']

,Season,Week,GameStatus,GameSlot,GameDate,AwayTeam,AwayScore,HomeTeam,HomeScore
2433,2016,WEEK 10,FINAL,Thursday,November 10th,CLE,7.0,BAL,28.0
2434,2016,WEEK 10,FINAL,Sunday,November 13th,KC,20.0,CAR,17.0
2435,2016,WEEK 10,FINAL,Sunday,November 13th,HOU,24.0,JAC,21.0
2436,2016,WEEK 10,FINAL,Sunday,November 13th,DEN,25.0,NO,23.0
2437,2016,WEEK 10,FINAL,Sunday,November 13th,LAR,9.0,NYJ,6.0
2438,2016,WEEK 10,FINAL,Sunday,November 13th,ATL,15.0,PHI,24.0
2439,2016,WEEK 10,FINAL,Sunday,November 13th,CHI,10.0,TB,36.0
2440,2016,WEEK 10,FINAL,Sunday,November 13th,GB,25.0,TEN,47.0
2441,2016,WEEK 10,FINAL,Sunday,November 13th,MIN,20.0,WAS,26.0
2442,2016,WEEK 10,FINAL,Sunday,November 13th,MIA,31.0,SD,24.0
2443,2016,WEEK 10,FINAL,Sunday,November 13th,SF,20.0,ARI,23.0
2444,2016,WEEK 10,FINAL,Sunday,November 13th,DAL,35.0,PIT,30.0
2445,2016,WEEK 10,FINAL,Sunday,November 13th,SEA,31.0,NE,24.0
2446,2016,WEEK 10,FINAL,Monday,November 14th,CIN,20.0,NYG,21.0

In [293]:
df_2016.shape
# 256 juegos esa temporada

(256, 9)

In [294]:
df_2016 = df_2016.drop(columns=['GameStatus', 'GameSlot', 'GameDate', 'Season'])

df_2016.head()

        Week AwayTeam  AwayScore HomeTeam  HomeScore
2278  WEEK 1      CAR       20.0      DEN       21.0
2279  WEEK 1       TB       31.0      ATL       24.0
2280  WEEK 1      BUF        7.0      BAL       13.0
2281  WEEK 1      CHI       14.0      HOU       23.0
2282  WEEK 1       GB       27.0      JAC       23.0

In [295]:
df_2016['Margin'] = df_2016['HomeScore'] - df_2016['AwayScore']

df_2016.head()

        Week AwayTeam  AwayScore HomeTeam  HomeScore  Margin
2278  WEEK 1      CAR       20.0      DEN       21.0     1.0
2279  WEEK 1       TB       31.0      ATL       24.0    -7.0
2280  WEEK 1      BUF        7.0      BAL       13.0     6.0
2281  WEEK 1      CHI       14.0      HOU       23.0     9.0
2282  WEEK 1       GB       27.0      JAC       23.0    -4.0

In [296]:
# Crear el dataset de los ratings

teams = df_2016['HomeTeam'].unique()

teams

array(['DEN', 'ATL', 'BAL', 'HOU', 'JAC', 'KC', 'NO', 'NYJ', 'PHI', 'TEN',
       'SEA', 'DAL', 'IND', 'ARI', 'WAS', 'SF', 'BUF', 'CAR', 'CLE',
       'DET', 'NE', 'NYG', 'PIT', 'LAR', 'OAK', 'SD', 'MIN', 'CHI', 'CIN',
       'GB', 'MIA', 'TB'], dtype=object)

# Least Square Ratings

Tenemos un conjunto de equipos en una competencia. Y queremos rankear esos equipos basandonos en sus resultados previos en la liga, basandonos en los margenes de victoria a lo largo de un calendario. 

La idea es asignar un rating objectivo en cuanta diferencia o que tan fuerte es un equipo con el resto de la liga.

Asumimos que el margen esperado de victoria en cualquier juego es directamente proporcional a la diferencia de los ratings de los rivales

$$ E[Y] = r_{home} - r_{away}$$

Siendo $Y$ una variable aleatoria que representa el margen de victoria entre dos equipos uno local y otro visitante.

Esta suposición implica que existe un ranking verdadero para cada equipo de tal manera que se cumple la exprsión: $ E[Y] = r_{home} - r_{away}$.


La meta de aisgnar ratings a los equipos, para explicar "mejor" los juegos completados, es equivalente a una multivarible regresion lineal observable.

Definición de una regresión lineal: 

$$ Y = \beta_0 + \beta_1 X_1 + ... + \beta_{m} X_m + \epsilon $$

Donde : 

- $Y$ es la variable dependiente o la variable de respuesta.
- $X_1$ , $X_2$ , ... , $X_m$ son la variables explicativas, independientes, o regresoras.
- $\beta_0 , \beta_1, ..., \beta_m$ son los parametros del modelo, miden la influencia que las variables explicativas tienen sobre el regrendio.

Usando esta definición podemos escribirla en nuestro terminos para este caso:

$$ y_i = r_0 + r_1 x_{i1} + ... + r_n x_{in} + \epsilon $$

Donde y:

- $y_i$ es la diferencia de puntos para el juego $i$
- Los $r$'s son los ratings que van a ser los parametros del modelo, con $r_0$ como la constante de home advantaje.
- Cada uno de los $n$ equipos es representado por es representado por una variable independiente predecible, donde puede tomar los valores 1, -1, 0. 1 para el equipo local, -1 para el equipo visitante, y 0 cuando ese equipo no participa en el juego $i$

Esto nos lleva a tener la ecuación de la predicción para un juego $i$:

$$ y_i = r_0 + r_{home} - r_{away} + \epsilon_{i} $$

Esto nos da la ecuación del libro:

Prediction Margin = (Home Edge) + (Home Team Rating) - (Away Team Rating)

Entonces el termino de error nos queda como:

$$ \epsilon_{i} = y_i - (r_0 + r_{home}  - r_{away} ) $$

Donde $r$ son los parametros de la regresion, que son obtenidos minimizando el error cuadrado: $ \sum \epsilon^{2}_{i} $


Si escribimos nuestro problema de forma matricial:

$$ \textbf{Y} = \textbf{X} \textbf{r} + \varepsilon $$

Si seguimos las matematicas de minimos cuadrados podemos resolver el sistema con:

$$ \textbf{r} = \textbf{X}^{+} \textbf{Y} $$

Donde $\textbf{X}^{+}$ es la pseudo inversa de $\textbf{X}$

In [297]:
df_2016

         Week AwayTeam  AwayScore HomeTeam  HomeScore  Margin
2278   WEEK 1      CAR       20.0      DEN       21.0     1.0
2279   WEEK 1       TB       31.0      ATL       24.0    -7.0
2280   WEEK 1      BUF        7.0      BAL       13.0     6.0
2281   WEEK 1      CHI       14.0      HOU       23.0     9.0
2282   WEEK 1       GB       27.0      JAC       23.0    -4.0
...       ...      ...        ...      ...        ...     ...
2561  WEEK 17      OAK        6.0      DEN       24.0    18.0
2562  WEEK 17      ARI       44.0      LAR        6.0   -38.0
2563  WEEK 17       KC       37.0       SD       27.0   -10.0
2564  WEEK 17      SEA       25.0       SF       23.0    -2.0
2565  WEEK 17       GB       31.0      DET       24.0    -7.0

[256 rows x 6 columns]

In [298]:
# Hay que construir la matriz X y el vector y

y = df_2016['Margin'].to_numpy()

y.shape

(256,)

In [299]:
# Hay que mapear los equipos a un directorio, hay que tener una lista por orden alfabetico

teams = sorted(teams)

teams

['ARI',
 'ATL',
 'BAL',
 'BUF',
 'CAR',
 'CHI',
 'CIN',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GB',
 'HOU',
 'IND',
 'JAC',
 'KC',
 'LAR',
 'MIA',
 'MIN',
 'NE',
 'NO',
 'NYG',
 'NYJ',
 'OAK',
 'PHI',
 'PIT',
 'SD',
 'SEA',
 'SF',
 'TB',
 'TEN',
 'WAS']

In [300]:
teams_to_idx = {}

for i in range(len(teams)):
    teams_to_idx[teams[i]] = i + 1

teams_to_idx

{'ARI': 1,
 'ATL': 2,
 'BAL': 3,
 'BUF': 4,
 'CAR': 5,
 'CHI': 6,
 'CIN': 7,
 'CLE': 8,
 'DAL': 9,
 'DEN': 10,
 'DET': 11,
 'GB': 12,
 'HOU': 13,
 'IND': 14,
 'JAC': 15,
 'KC': 16,
 'LAR': 17,
 'MIA': 18,
 'MIN': 19,
 'NE': 20,
 'NO': 21,
 'NYG': 22,
 'NYJ': 23,
 'OAK': 24,
 'PHI': 25,
 'PIT': 26,
 'SD': 27,
 'SEA': 28,
 'SF': 29,
 'TB': 30,
 'TEN': 31,
 'WAS': 32}

In [301]:
df_2016.reset_index(drop=True, inplace=True)

df_2016

        Week AwayTeam  AwayScore HomeTeam  HomeScore  Margin
0     WEEK 1      CAR       20.0      DEN       21.0     1.0
1     WEEK 1       TB       31.0      ATL       24.0    -7.0
2     WEEK 1      BUF        7.0      BAL       13.0     6.0
3     WEEK 1      CHI       14.0      HOU       23.0     9.0
4     WEEK 1       GB       27.0      JAC       23.0    -4.0
..       ...      ...        ...      ...        ...     ...
251  WEEK 17      OAK        6.0      DEN       24.0    18.0
252  WEEK 17      ARI       44.0      LAR        6.0   -38.0
253  WEEK 17       KC       37.0       SD       27.0   -10.0
254  WEEK 17      SEA       25.0       SF       23.0    -2.0
255  WEEK 17       GB       31.0      DET       24.0    -7.0

[256 rows x 6 columns]

In [302]:
X = np.zeros((256, 33))

for i, game in df_2016.iterrows():
    # 1 en la primer columna para el r0
    X[i][0] = 1

    # 1 para el equipo local
    X[i][teams_to_idx[game['HomeTeam']]] = 1

    # -1 para el equipo visitante
    X[i][teams_to_idx[game['AwayTeam']]] = -1

Para garantizar una solución unica se añade una nueva ecuación como restricción 

$$ r_0 + r_1 + ... + r_m = c = 0$$

In [303]:
# Add the m + 1 ecuation r0 + r1 + ... + r3 = c = 0

X = np.vstack((X, np.ones(33)))

X.shape

(257, 33)

In [304]:
y = np.append(y, np.zeros(1))

y.shape

(257,)

In [305]:
X_pseudoinv = np.linalg.pinv(X)

r = X_pseudoinv.dot(y)

In [306]:
HOME_EDGE = r[0]

print(f"Home Edge : {HOME_EDGE}")

Home Edge : 2.5664062499999982

In [307]:
df_ratings = pd.DataFrame({ 'Team' : teams , 'Rating' : r[1:]})

df_ratings['Rank_LS'] = df_ratings['Rating'].rank(ascending=False) 

df_ratings

   Team     Rating  Rank_LS
0   ARI   1.509730     13.0
1   ATL   8.402091      2.0
2   BAL   1.457126     15.0
3   BUF  -0.412318     21.0
4   CAR  -1.082631     22.0
5   CHI  -7.580895     28.0
6   CIN   0.964071     16.0
7   CLE -10.167527     30.0
8   DAL   6.889244      3.0
9   DEN   3.967196      6.0
10  DET  -1.477422     24.0
11   GB   2.753480      9.0
12  HOU  -2.707804     26.0
13  IND   0.286293     18.0
14  JAC  -5.048082     27.0
15   KC   5.516848      4.0
16  LAR -11.167006     31.0
17  MIA  -2.481415     25.0
18  MIN   0.863203     17.0
19   NE   9.205737      1.0
20   NO   1.462855     14.0
21  NYG   2.048272     11.0
22  NYJ  -8.597388     29.0
23  OAK   3.182473      8.0
24  PHI   3.723619      7.0
25  PIT   4.660946      5.0
26   SD  -0.022735     19.0
27  SEA   2.050008     10.0
28   SF -11.292700     32.0
29   TB  -0.273950     20.0
30  TEN  -1.086624     23.0
31  WAS   1.888897     12.0

In [308]:
team_to_rating = {}

for inx, team in df_ratings.iterrows():
    team_to_rating[team['Team']] = team['Rating']

print(team_to_rating)

{'ARI': 1.5097303602430618, 'ATL': 8.402091471354176, 'BAL': 1.457126193576396, 'BUF': -0.41231825086805207, 'CAR': -1.0826307508680335, 'CHI': -7.580894639756951, 'CIN': 0.9640706380208242, 'CLE': -10.16752658420139, 'DAL': 6.889244249131917, 'DEN': 3.967195638020845, 'DET': -1.4774224175347292, 'GB': 2.7534803602430546, 'HOU': -2.707804361979189, 'IND': 0.286292860243033, 'JAC': -5.0480821397569535, 'KC': 5.516848415798627, 'LAR': -11.167005750868075, 'MIA': -2.4814154730902658, 'MIN': 0.8632025824652501, 'NE': 9.205737304687492, 'NO': 1.4628553602430623, 'NYG': 2.0482720269097223, 'NYJ': -8.597387695312511, 'OAK': 3.1824734157986216, 'PHI': 3.7236192491319393, 'PIT': 4.660945638020834, 'SD': -0.022734917534706245, 'SEA': 2.050008138020837, 'SF': -11.292700195312507, 'TB': -0.27395019531248854, 'TEN': -1.0866238064236073, 'WAS': 1.8888970269097292}

In [309]:
rating_map = df_ratings.set_index('Team')['Rating']

print(rating_map)

df_2016['Prediction'] = (
    HOME_EDGE
    + df_2016['HomeTeam'].map(rating_map)
    - df_2016['AwayTeam'].map(rating_map)
)

Team
ARI     1.509730
ATL     8.402091
BAL     1.457126
BUF    -0.412318
CAR    -1.082631
CHI    -7.580895
CIN     0.964071
CLE   -10.167527
DAL     6.889244
DEN     3.967196
DET    -1.477422
GB      2.753480
HOU    -2.707804
IND     0.286293
JAC    -5.048082
KC      5.516848
LAR   -11.167006
MIA    -2.481415
MIN     0.863203
NE      9.205737
NO      1.462855
NYG     2.048272
NYJ    -8.597388
OAK     3.182473
PHI     3.723619
PIT     4.660946
SD     -0.022735
SEA     2.050008
SF    -11.292700
TB     -0.273950
TEN    -1.086624
WAS     1.888897
Name: Rating, dtype: float64

In [310]:
df_2016['Squared Error'] = (df_2016['Margin'] - df_2016['Prediction'])**2

df_2016

,Week,AwayTeam,AwayScore,HomeTeam,HomeScore,Margin,Prediction,Squared Error
0,WEEK 1,CAR,20.0,DEN,21.0,1.0,7.616233,43.774534
1,WEEK 1,TB,31.0,ATL,24.0,-7.0,11.242448,332.786906
2,WEEK 1,BUF,7.0,BAL,13.0,6.0,4.435851,2.446563
3,WEEK 1,CHI,14.0,HOU,23.0,9.0,7.439497,2.435171
4,WEEK 1,GB,27.0,JAC,23.0,-4.0,-5.235156,1.525611
...,...,...,...,...,...,...,...,...
251,WEEK 17,OAK,6.0,DEN,24.0,18.0,3.351128,214.589437
252,WEEK 17,ARI,44.0,LAR,6.0,-38.0,-10.110330,777.833700
253,WEEK 17,KC,37.0,SD,27.0,-10.0,-2.973177,49.376240
254,WEEK 17,SEA,25.0,SF,23.0,-2.0,-10.776302,77.023478
255,WEEK 17,GB,31.0,DET,24.0,-7.0,-1.664497,28.467597

# Evaluating Strength of Schedule

Basicamente para asignar un rating basado en el la fuerza del calendario, hay que sumar el rating anterior de todos sus rivales y dividirlo entre 16 (total de juegos)

In [311]:
df_schedule_strength = df_ratings.copy()

df_schedule_strength

   Team     Rating  Rank_LS
0   ARI   1.509730     13.0
1   ATL   8.402091      2.0
2   BAL   1.457126     15.0
3   BUF  -0.412318     21.0
4   CAR  -1.082631     22.0
5   CHI  -7.580895     28.0
6   CIN   0.964071     16.0
7   CLE -10.167527     30.0
8   DAL   6.889244      3.0
9   DEN   3.967196      6.0
10  DET  -1.477422     24.0
11   GB   2.753480      9.0
12  HOU  -2.707804     26.0
13  IND   0.286293     18.0
14  JAC  -5.048082     27.0
15   KC   5.516848      4.0
16  LAR -11.167006     31.0
17  MIA  -2.481415     25.0
18  MIN   0.863203     17.0
19   NE   9.205737      1.0
20   NO   1.462855     14.0
21  NYG   2.048272     11.0
22  NYJ  -8.597388     29.0
23  OAK   3.182473      8.0
24  PHI   3.723619      7.0
25  PIT   4.660946      5.0
26   SD  -0.022735     19.0
27  SEA   2.050008     10.0
28   SF -11.292700     32.0
29   TB  -0.273950     20.0
30  TEN  -1.086624     23.0
31  WAS   1.888897     12.0

In [312]:
print(team_to_rating)

{'ARI': 1.5097303602430618, 'ATL': 8.402091471354176, 'BAL': 1.457126193576396, 'BUF': -0.41231825086805207, 'CAR': -1.0826307508680335, 'CHI': -7.580894639756951, 'CIN': 0.9640706380208242, 'CLE': -10.16752658420139, 'DAL': 6.889244249131917, 'DEN': 3.967195638020845, 'DET': -1.4774224175347292, 'GB': 2.7534803602430546, 'HOU': -2.707804361979189, 'IND': 0.286292860243033, 'JAC': -5.0480821397569535, 'KC': 5.516848415798627, 'LAR': -11.167005750868075, 'MIA': -2.4814154730902658, 'MIN': 0.8632025824652501, 'NE': 9.205737304687492, 'NO': 1.4628553602430623, 'NYG': 2.0482720269097223, 'NYJ': -8.597387695312511, 'OAK': 3.1824734157986216, 'PHI': 3.7236192491319393, 'PIT': 4.660945638020834, 'SD': -0.022734917534706245, 'SEA': 2.050008138020837, 'SF': -11.292700195312507, 'TB': -0.27395019531248854, 'TEN': -1.0866238064236073, 'WAS': 1.8888970269097292}

In [316]:
schedule_strenght = {team : 0 for team in team_to_rating}


for idx, game in df_2016.iterrows():
    schedule_strenght[game['HomeTeam']] += team_to_rating[game['AwayTeam']]
    schedule_strenght[game['AwayTeam']] += team_to_rating[game['HomeTeam']]


schedule_strenght = {team: total / 16 for team, total in schedule_strenght.items()}

df_ratings['schedule_strength'] = df_ratings['Team'].map(schedule_strenght)

df_ratings['Rank_SS'] = df_ratings['schedule_strength'].rank(ascending=False)

df_ratings

   Team     Rating  Rank_LS  schedule_strength  Rank_SS
0   ARI   1.509730     13.0          -1.990270     31.0
1   ATL   8.402091      2.0           0.027091     17.0
2   BAL   1.457126     15.0           0.082126     15.0
3   BUF  -0.412318     21.0          -1.724818     29.0
4   CAR  -1.082631     22.0           0.979869      6.0
5   CHI  -7.580895     28.0          -0.080895     19.0
6   CIN   0.964071     16.0           0.339071     13.0
7   CLE -10.167527     30.0           1.582473      2.0
8   DAL   6.889244      3.0          -0.298256     21.0
9   DEN   3.967196      6.0           1.717196      1.0
10  DET  -1.477422     24.0          -0.727422     25.0
11   GB   2.753480      9.0           0.003480     18.0
12  HOU  -2.707804     26.0           0.354696     12.0
13  IND   0.286293     18.0          -0.901207     26.0
14  JAC  -5.048082     27.0           0.076918     16.0
15   KC   5.516848      4.0           0.641848      9.0
16  LAR -11.167006     31.0          -0.542006     23.0
17  MIA  -2.481415     25.0          -1.418915     28.0
18  MIN   0.863203     17.0          -0.386797     22.0
19   NE   9.205737      1.0          -2.731763     32.0
20   NO   1.462855     14.0           0.525355     10.0
21  NYG   2.048272     11.0           0.423272     11.0
22  NYJ  -8.597388     29.0          -0.222388     20.0
23  OAK   3.182473      8.0           1.244973      4.0
24  PHI   3.723619      7.0           1.473619      3.0
25  PIT   4.660946      5.0           0.160946     14.0
26   SD  -0.022735     19.0           0.789765      7.0
27  SEA   2.050008     10.0          -1.824992     30.0
28   SF -11.292700     32.0          -0.605200     24.0
29   TB  -0.273950     20.0           0.663550      8.0
30  TEN  -1.086624     23.0          -1.274124     27.0
31  WAS   1.888897     12.0           1.076397      5.0

# Ranking Teams based on Mean Absolute Errors